insert into Carrier (CarrierName, City) select 'Ace Courier', 'Unknown'
insert into Carrier (CarrierName, City) select 'Ace', 'Unknown'
insert into Carrier (CarrierName, City) select 'APPS Cargo', 'Unknown'
insert into Carrier (CarrierName, City) select 'Bandstra', 'Unknown'
insert into Carrier (CarrierName, City) select 'Berry & Smith', 'Unknown'
insert into Carrier (CarrierName, City) select 'Canadian Freightways', 'Unknown'
insert into Carrier (CarrierName, City) select 'Clark Freightways', 'Unknown'
insert into Carrier (CarrierName, City) select 'Customer P/U', 'Unknown'
insert into Carrier (CarrierName, City) select 'Customer Pick up', 'Unknown'
insert into Carrier (CarrierName, City) select 'Day & Ross', 'Unknown'
insert into Carrier (CarrierName, City) select 'DHL', 'Unknown'
insert into Carrier (CarrierName, City) select 'Diamond Delivery', 'Unknown'
insert into Carrier (CarrierName, City) select 'Get Quote for Customer', 'Unknown'
insert into Carrier (CarrierName, City) select 'Greyhound', 'Unknown'
insert into Carrier (CarrierName, City) select 'Jays', 'Unknown'
insert into Carrier (CarrierName, City) select 'Kindersley', 'Unknown'
insert into Carrier (CarrierName, City) select 'Manitoulin Transport', 'Unknown'
insert into Carrier (CarrierName, City) select 'Overland', 'Unknown'
insert into Carrier (CarrierName, City) select 'Overland/B & R Eckels', 'Unknown'
insert into Carrier (CarrierName, City) select 'Overland/Bandstra', 'Unknown'
insert into Carrier (CarrierName, City) select 'Overland/Comox Pacific', 'Unknown'
insert into Carrier (CarrierName, City) select 'Overland/Grimshaw', 'Unknown'
insert into Carrier (CarrierName, City) select 'Overland/Roseneau', 'Unknown'
insert into Carrier (CarrierName, City) select 'Purolator', 'Unknown'
insert into Carrier (CarrierName, City) select 'Reimer Express', 'Unknown'
insert into Carrier (CarrierName, City) select 'Rogmay Services', 'Unknown'
insert into Carrier (CarrierName, City) select 'Rogmay', 'Unknown'
insert into Carrier (CarrierName, City) select 'Rosenau', 'Unknown'
insert into Carrier (CarrierName, City) select 'Tiger', 'Unknown'
insert into Carrier (CarrierName, City) select 'Van Kam', 'Unknown'
insert into Carrier (CarrierName, City) select 'VanKam/Mustang', 'Unknown'
insert into Carrier (CarrierName, City) select 'Vitran', 'Unknown'
insert into Carrier (CarrierName, City) select 'Will Advise', 'Unknown'